# Generated by Django 3.0.4 on 2020-05-25 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontents',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
