# Generated by Django 3.0.7 on 2020-07-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='request_user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
