# Generated by Django 3.0.4 on 2020-05-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assy', '0002_auto_20200525_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.TextField(blank=True, default='img/icon_default.jpg'),
        ),
        migrations.AlterField(
            model_name='postcontents',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
