# Generated by Django 3.0.4 on 2020-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assy', '0003_auto_20200526_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.TextField(blank=True, default='icon_default.jpg'),
        ),
    ]
