# Generated by Django 3.0.4 on 2020-05-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assy', '0004_auto_20200526_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontents',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
