# Generated by Django 3.0.4 on 2020-05-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assy', '0006_auto_20200526_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
