# Generated by Django 3.0.7 on 2020-06-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assy', '0007_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontents',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
